language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
stages:
  - Build
  - Compile
  - name: Verify
    if: branch=master
  - name: Deploy
    if: branch=develop
jobs:
  include:
    - stage: Build
      name: "maven: Make a clean install"
      script: mvn clean install